In [13]:
import numpy as np

from tensorflow.keras.models import *
from tensorflow.keras.layers import *
from tensorflow.keras.optimizers import *
from tensorflow.keras.losses import *
from tensorflow.keras.utils import *

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

In [14]:
dataset = load_digits()
x = dataset.data
y = dataset.target

print(x.shape)
print(y.shape)

print(x[0])
print(y[0])

print(f"y before:\n{y}")
y = to_categorical(y, num_classes=10)
print(f"y after:\n{y}")

x_train, x_test, y_train, y_test = train_test_split(x,y)

(1797, 64)
(1797,)
[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
0
y before:
[0 1 2 ... 8 9 8]
y after:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]]


In [17]:
model = Sequential()
model.add(Dense(512, input_dim=x.shape[1])) # Input Layer(64 Neurons) to first Hidden Layer (512 Neurons)
model.add(Activation("relu"))
model.add(Dense(256))
model.add(Activation("relu"))
model.add(Dense(y.shape[1])) # Last Hidden Layer (256 Neurons) to Output Layer => 10 Neurons
model.add(Activation("softmax"))

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 512)               33280     
_________________________________________________________________
activation_6 (Activation)    (None, 512)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 256)               131328    
_________________________________________________________________
activation_7 (Activation)    (None, 256)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 10)                2570      
_________________________________________________________________
activation_8 (Activation)    (None, 10)                0         
Total params: 167,178
Trainable params: 167,178
Non-trainable params: 0
________________________________________________

In [21]:
sgd = SGD(lr=0.0001)
model.compile(loss="categorical_crossentropy", optimizer=sgd, metrics=["accuracy"])
model.fit(x=x_train, y=y_train, epochs=45, validation_data=(x_test, y_test))

Epoch 1/45
43/43 [==============================] - 0s 4ms/step - loss: 0.0108 - accuracy: 1.0000 - val_loss: 0.0901 - val_accuracy: 0.9733
Epoch 2/45
43/43 [==============================] - 0s 2ms/step - loss: 0.0107 - accuracy: 1.0000 - val_loss: 0.0898 - val_accuracy: 0.9733
Epoch 3/45
43/43 [==============================] - 0s 2ms/step - loss: 0.0106 - accuracy: 1.0000 - val_loss: 0.0894 - val_accuracy: 0.9733
Epoch 4/45
43/43 [==============================] - 0s 1ms/step - loss: 0.0105 - accuracy: 1.0000 - val_loss: 0.0891 - val_accuracy: 0.9733
Epoch 5/45
43/43 [==============================] - 0s 1ms/step - loss: 0.0105 - accuracy: 1.0000 - val_loss: 0.0888 - val_accuracy: 0.9733
Epoch 6/45
43/43 [==============================] - 0s 1ms/step - loss: 0.0104 - accuracy: 1.0000 - val_loss: 0.0889 - val_accuracy: 0.9733
Epoch 7/45
43/43 [==============================] - 0s 2ms/step - loss: 0.0103 - accuracy: 1.0000 - val_loss: 0.0887 - val_accuracy: 0.9733
Epoch 8/45
43/43 [==